@startuml name Ejercicio3_LRP

left to right direction 

actor Obrero
actor Encargado


usecase "Preparar terreno para siembra" as UC1    
usecase "Sembrar" as UC2    
usecase "Controlar Cosecha" as UC3    
usecase "Informe de plaga" as UC31    
usecase "Recolectar Cosecha" as UC4
usecase "Enviar Cosecha a almacen" as UC5  
usecase "Solicitar Material para la siembra" as UC6  
usecase "Solicitar Semillas" as UC7  
usecase "Solicitar Abonos" as UC8  
usecase "Solicitar Maquinaria" as UC9  

Obrero --> UC1
Obrero --> UC2
Obrero --> UC3
Obrero --> UC4
Obrero --> UC5

Encargado --> UC7
Encargado --> UC8
Encargado --> UC9
Encargado --> UC31


UC31 -->UC3 
UC7 --> UC6
UC8 --> UC6
UC9 --> UC6

UC1 ..> UC6 : <<extend>>\n[Si es necesario]


@enduml
