@startuml name Ejercicio1_LRP
left to right direction 

actor Administrativo
actor Chofer
actor Gerente


usecase "Alta reserva" as UC1    
usecase "Consulta datos chofer" as UC2
usecase "Confirmar reserva" as UC3  
usecase "Cancelar reserva" as UC4  
usecase "Consulta reserva" as UC5  
usecase "Alta Chofer" as UC6  
usecase "Liquidar comisiones" as UC7 
usecase "Alta clientes" as UC8 

Administrativo --> UC1
Administrativo --> UC2
Administrativo --> UC3
Administrativo --> UC4

Chofer --> UC5

Gerente --> UC6
Gerente --> UC7
Gerente --> UC2

UC1 ..> UC8 : <<extend>>\n[Si no existe el cliente]

@enduml
