@startuml name Ejemplo3

actor Usuario
participant Estacion
participant Sistema
participant "Pasarela de pago" as Pago

Usuario -> Estacion : Insertar bicicleta
Estacion -> Sistema : Notificar devolución

Sistema -> Estacion : Bloquear bicicleta
Estacion --> Sistema : Confirmación bloqueo

Sistema -> Sistema : Calcular coste del trayecto

Sistema -> Pago : Solicitar cobro
Pago --> Sistema : Confirmación pago

Sistema --> Usuario : Devolución finalizada

@enduml