@startuml name Ejemplo1_LRP
left to right direction

actor Camarero
actor Cliente
actor Cocinero

usecase "Tomar orden" as UC1
usecase "Preparar comida" as UC2    
usecase "Servir comida" as UC3
usecase "Pagar cuenta" as UC4       

usecase "Rehacer comanda" as UC5
usecase "Registrar en lista de morosos" as UC6

Camarero --> UC1
Camarero --> UC3        
Cliente --> UC4
Cocinero --> UC2    

UC1 --> UC2 : <<include>>
UC2 --> UC3 : <<include>>
UC3 --> UC4 : <<include>>

UC5 ..> UC2 : <<extend>>\n[No hay plato disponible]
UC6 ..> UC4 : <<extend>>\n[Cliente no paga]
' EL EXTEND ES EL OPCIONAL
'LO QUE ESTA ENTRE CORCHETES SON LOS COMENTARIOS

@enduml