@startuml name Ejemplo2
left to right direction

actor Usuario
actor Sistema
actor "Técnico mantenimiento" as Tecnico

usecase "Alquilar bicicleta" as UC1
usecase "Devolver bicicleta" as UC2

usecase "Identificarse" as UC3
usecase "Comprobar saldo" as UC4
usecase "Desbloquear bicicleta" as UC5

usecase "Bloquear bicicleta" as UC6
usecase "Calcular coste" as UC7
usecase "Cobrar importe" as UC8

usecase "Sugerir estación cercana" as UC9
usecase "Avisar a mantenimiento" as UC10
usecase "Bloquear cuenta usuario" as UC11
usecase "Aplicar bono mensual" as UC12

Usuario --> UC1
Usuario --> UC2

UC1 --> UC3 : <<include>>
UC1 --> UC4 : <<include>>
UC1 --> UC5 : <<include>>

UC2 --> UC6 : <<include>>
UC2 --> UC7 : <<include>>
UC2 --> UC8 : <<include>>

UC9 ..> UC1 : <<extend>>\n[No hay bicicletas]
UC10 ..> UC2 : <<extend>>\n[Bici averiada]
UC11 ..> UC8 : <<extend>>\n[Pago fallido]
UC12 ..> UC8 : <<extend>>\n[Usuario con bono]

Tecnico --> UC10

@enduml