@startuml name Ejemplo0_LRP
left to right direction 
'INDICA QUE VA DE IZQUIERDA A DERECHA

actor Camarero
actor Cliente
actor Cocinero
'LOS ACTORES MONIGOTES
usecase "Tomar orden" as UC1
usecase "Preparar comida" as UC2    
usecase "Servir comida" as UC3
usecase "Pagar cuenta" as UC4       
'LOS BOCADILLOS CON EL AS (ALIAS)

Camarero --> UC1
Camarero --> UC3        
Cliente --> UC4
Cocinero --> UC2
' LAS FLECHAS O LO QUE PUEDES HACER DESDE EL USUARIO CORRESPONDIENTE    

UC1 --> UC2 : <<include>>
UC2 --> UC3 : <<include>>
UC3 --> UC4 : <<include>>

'LAS PREFERENCIA, SECUENCIAS, PRIORIDADES....
' EL INCLUDE SIGNIFICA QUE ES OBLIGATORIO NO ES OPCIONAL
' EL EXTEND ES EL OPCIONAL

@enduml